### ISSUE TITLE
Support for AWS::CloudFormation::Interface

### ISSUE THREAD

**Issue by bjorg** [jakejscott/Humidifier#10]
Using `Humidifier v0.2.15`

It doesn't seem to be currently possible to generate a `Metadata`  stack entry. AFAIK, this is only used for the `AWS::CloudFormation::Interface` resource type which is handled in a really unusual manner.

```yaml
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCID
          - SubnetId
          - SecurityGroupID
      - 
        Label: 
          default: "Amazon EC2 Configuration"
        Parameters: 
          - InstanceType
          - KeyName
    ParameterLabels: 
      VPCID: 
        default: "Which VPC should this be deployed to?"
```

See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html
